### ISSUE TITLE
Way of converting pixel to ascii

### ISSUE THREAD

**Issue by Perchinka** [nis-sin/Image-to-Ascii#1]
Using lots of if-statements is considered not really elegant way of writing code :) 

So just a small tip, you can consider selecting the desired ascii char for pixel from the list using **list_of_ascii[brightness_of_pixel // 25 (_here you can define your step_)]**  method for example. Probably out there exists even better solution, but in case when you have equal step between light-levels you can use this method, it's good enough

**Comment by Perchinka** [comment]
```python
def pixelToAscii(pixelBrightness: int) -> str:
    ascii = ["@", "#", "%", "?", "*", "+", ";", "."]
    # greyscale value will be used as pixel brightness, values range from 0 to 255
    if pixelBrightness > 230:
        return ascii[0]
    elif pixelBrightness > 200:
        return ascii[1]
    elif pixelBrightness > 170:
        return ascii[2]
    elif pixelBrightness > 140:
        return ascii[3]
    elif pixelBrightness > 110:
        return ascii[4]
    elif pixelBrightness > 80:
        return ascii[5]
    elif pixelBrightness > 50:
        return ascii[6]
    else:
        return ascii[7]
  ```

**Comment by n12g** [comment]
I didn't think about using floor division. Thanks, I will make the changes now.
